name: colorist_ui
description: "A Flutter library of UI components for an LLM codelab."
version: 0.2.2
repository: https://github.com/domesticmouse/colorist_ui

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
